/**
 * 火山引擎豆包 TTS 音色表(内置参考,供 list-voices 与 config 校验)。
 * 数据来源:docs/tech_stack/tts/volcengine/voices.md(抓取 2026-08-14,过期 D+90)。
 * 生成:脚本一次性从抓取结果导出,勿手改;更新时重跑生成器。
 * @module dsh-voice-tts/voices
 */

import type { TtsVoice } from "./types.js"

/** volcengine 全部 seed-tts-2.0 音色(标准 93 + 多语种 137)。 */
export const VOLCENGINE_VOICES: readonly TtsVoice[] = [
  { voice_type: "zh_female_vv_uranus_bigtts", name: "Vivi 2.0", scene: "通用场景", lang: "语种：中文、日文、印尼、墨西哥西班牙语 方言：粤语、上海、河南、北京、天津、四川、陕西、东北", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_xiaohe_uranus_bigtts", name: "小何 2.0", scene: "通用场景", lang: "语种：中文 方言：粤语、上海、河南、北京、天津、四川、陕西、东北", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_m191_uranus_bigtts", name: "云舟 2.0", scene: "通用场景", lang: "语种：中文 方言：粤语、上海、河南、北京、天津、四川、陕西、东北", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_taocheng_uranus_bigtts", name: "小天 2.0", scene: "通用场景", lang: "语种：中文 方言：粤语、上海、河南、北京、天津、四川、陕西、东北", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_liufei_uranus_bigtts", name: "刘飞 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_sophie_uranus_bigtts", name: "魅力苏菲 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_qingxinnvsheng_uranus_bigtts", name: "清新女声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_cancan_uranus_bigtts", name: "知性灿灿 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_sajiaoxuemei_uranus_bigtts", name: "撒娇学妹 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_tianmeixiaoyuan_uranus_bigtts", name: "甜美小源 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_tianmeitaozi_uranus_bigtts", name: "甜美桃子 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_shuangkuaisisi_uranus_bigtts", name: "爽快思思 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_peiqi_uranus_bigtts", name: "佩奇猪 2.0", scene: "视频配音", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_female_linjianvhai_uranus_bigtts", name: "邻家女孩 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_shaonianzixin_uranus_bigtts", name: "少年梓辛 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_sunwukong_uranus_bigtts", name: "猴哥 2.0", scene: "视频配音", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_yingyujiaoxue_uranus_bigtts", name: "Tina老师 2.0", scene: "教育场景", lang: "中文、英式英语", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_kefunvsheng_uranus_bigtts", name: "暖阳女声 2.0", scene: "客服场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_xiaoxue_uranus_bigtts", name: "儿童绘本 2.0", scene: "有声阅读", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_dayi_uranus_bigtts", name: "大壹 2.0", scene: "视频配音", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_mizai_uranus_bigtts", name: "黑猫侦探社咪仔 2.0", scene: "视频配音", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_jitangnv_uranus_bigtts", name: "鸡汤女 2.0", scene: "视频配音", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_meilinvyou_uranus_bigtts", name: "魅力女友 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_liuchangnv_uranus_bigtts", name: "流畅女声 2.0", scene: "视频配音", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_ruyayichen_uranus_bigtts", name: "儒雅逸辰 2.0", scene: "视频配音", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "en_male_tim_uranus_bigtts", name: "Tim", scene: "多语种", lang: "美式英语", ability: "指令遵循", group: "standard" },
  { voice_type: "en_female_dacey_uranus_bigtts", name: "Dacey", scene: "多语种", lang: "美式英语", ability: "指令遵循", group: "standard" },
  { voice_type: "en_female_stokie_uranus_bigtts", name: "Stokie", scene: "多语种", lang: "美式英语", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_wenroumama_uranus_bigtts", name: "温柔妈妈 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_jieshuoxiaoming_uranus_bigtts", name: "解说小明 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_tvbnv_uranus_bigtts", name: "TVB女声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_yizhipiannan_uranus_bigtts", name: "译制片男 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_qiaopinv_uranus_bigtts", name: "俏皮女声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_zhishuaiyingzi_uranus_bigtts", name: "直率英子 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_male_linjiananhai_uranus_bigtts", name: "邻家男孩 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_silang_uranus_bigtts", name: "四郎 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_male_ruyaqingnian_uranus_bigtts", name: "儒雅青年 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "番茄小说同款,豆包同款,剪映同款" },
  { voice_type: "zh_male_qingcang_uranus_bigtts", name: "擎苍 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "番茄小说同款,豆包同款,抖音同款,剪映同款" },
  { voice_type: "zh_male_xionger_uranus_bigtts", name: "熊二 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_female_yingtaowanzi_uranus_bigtts", name: "樱桃丸子 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_male_wennuanahu_uranus_bigtts", name: "温暖阿虎 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_naiqimengwa_uranus_bigtts", name: "奶气萌娃 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "剪映同款,豆包同款" },
  { voice_type: "zh_female_popo_uranus_bigtts", name: "婆婆 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_female_gaolengyujie_uranus_bigtts", name: "高冷御姐 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_aojiaobazong_uranus_bigtts", name: "傲娇霸总 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_lanyinmianbao_uranus_bigtts", name: "懒音绵宝 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_fanjuanqingnian_uranus_bigtts", name: "反卷青年 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_wenroushunv_uranus_bigtts", name: "温柔淑女 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "番茄小说同款,豆包同款,剪映同款" },
  { voice_type: "zh_female_gufengshaoyu_uranus_bigtts", name: "古风少御 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_huolixiaoge_uranus_bigtts", name: "活力小哥 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_baqiqingshu_uranus_bigtts", name: "霸气青叔 2.0", scene: "有声阅读", lang: "中文", ability: "指令遵循", group: "standard", tag: "番茄小说同款,豆包同款,剪映同款" },
  { voice_type: "zh_male_xuanyijieshuo_uranus_bigtts", name: "悬疑解说 2.0", scene: "有声阅读", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_female_mengyatou_uranus_bigtts", name: "萌丫头 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_tiexinnvsheng_uranus_bigtts", name: "贴心女声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_jitangmei_uranus_bigtts", name: "鸡汤妹妹 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款" },
  { voice_type: "zh_male_cixingjieshuonan_uranus_bigtts", name: "磁性解说男声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,剪映同款" },
  { voice_type: "zh_male_liangsangmengzai_uranus_bigtts", name: "亮嗓萌仔 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_kailangjiejie_uranus_bigtts", name: "开朗姐姐 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_gaolengchenwen_uranus_bigtts", name: "高冷沉稳 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "猫箱同款" },
  { voice_type: "zh_male_shenyeboke_uranus_bigtts", name: "深夜播客 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_lubanqihao_uranus_bigtts", name: "鲁班七号 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_female_jiaochuannv_uranus_bigtts", name: "娇喘女声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,剪映同款" },
  { voice_type: "zh_female_linxiao_uranus_bigtts", name: "林潇 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_female_lingling_uranus_bigtts", name: "玲玲姐姐 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_female_chunribu_uranus_bigtts", name: "春日部姐姐 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款,剪映同款" },
  { voice_type: "zh_male_tangseng_uranus_bigtts", name: "唐僧 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,豆包同款" },
  { voice_type: "zh_male_zhuangzhou_uranus_bigtts", name: "庄周 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,剪映同款" },
  { voice_type: "zh_male_kailangdidi_uranus_bigtts", name: "开朗弟弟 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,剪映同款" },
  { voice_type: "zh_male_zhubajie_uranus_bigtts", name: "猪八戒 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "豆包同款,剪映同款" },
  { voice_type: "zh_female_ganmaodianyin_uranus_bigtts", name: "感冒电音姐姐 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,剪映同款" },
  { voice_type: "zh_female_chanmeinv_uranus_bigtts", name: "谄媚女声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,剪映同款" },
  { voice_type: "zh_female_nvleishen_uranus_bigtts", name: "女雷神 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "剪映同款,豆包同款" },
  { voice_type: "zh_female_qinqienv_uranus_bigtts", name: "亲切女声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "豆包同款" },
  { voice_type: "zh_male_kuailexiaodong_uranus_bigtts", name: "快乐小东 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "豆包同款" },
  { voice_type: "zh_male_kailangxuezhang_uranus_bigtts", name: "开朗学长 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "豆包同款" },
  { voice_type: "zh_male_youyoujunzi_uranus_bigtts", name: "悠悠君子 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "豆包同款" },
  { voice_type: "zh_female_wenjingmaomao_uranus_bigtts", name: "文静毛毛 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "豆包同款" },
  { voice_type: "zh_female_zhixingnv_uranus_bigtts", name: "知性女声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_qingshuangnanda_uranus_bigtts", name: "清爽男大 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "豆包同款" },
  { voice_type: "zh_male_yuanboxiaoshu_uranus_bigtts", name: "渊博小叔 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_yangguangqingnian_uranus_bigtts", name: "阳光青年 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_qingchezizi_uranus_bigtts", name: "清澈梓梓 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_tianmeiyueyue_uranus_bigtts", name: "甜美悦悦 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_xinlingjitang_uranus_bigtts", name: "心灵鸡汤 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_wenrouxiaoge_uranus_bigtts", name: "温柔小哥 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_roumeinvyou_uranus_bigtts", name: "柔美女友 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_dongfanghaoran_uranus_bigtts", name: "东方浩然 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_wenrouxiaoya_uranus_bigtts", name: "温柔小雅 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_male_tiancaitongsheng_uranus_bigtts", name: "天才童声 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "zh_female_wuzetian_uranus_bigtts", name: "武则天 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "剪映同款" },
  { voice_type: "zh_female_gujie_uranus_bigtts", name: "顾姐 2.0", scene: "角色扮演", lang: "中文", ability: "指令遵循", group: "standard", tag: "抖音同款,剪映同款" },
  { voice_type: "zh_male_guanggaojieshuo_uranus_bigtts", name: "广告解说 2.0", scene: "通用场景", lang: "中文", ability: "指令遵循", group: "standard", tag: "剪映同款" },
  { voice_type: "zh_female_shaoergushi_uranus_bigtts", name: "少儿故事 2.0", scene: "有声阅读", lang: "中文", ability: "指令遵循", group: "standard" },
  { voice_type: "ar_female_dina_uranus_bigtts", name: "Dina", scene: "通用场景, 视频配音,多语种,阿拉伯语", lang: "阿拉伯语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ar_female_fatma_uranus_bigtts", name: "Fatma", scene: "趣味口音,多语种,阿拉伯语", lang: "阿拉伯语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ar_male_youssef_uranus_bigtts", name: "Youssef", scene: "通用场景,有声阅读,多语种,阿拉伯语", lang: "阿拉伯语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "de_female_bv081_uranus_bigtts", name: "Stella", scene: "教学场景, 客服场景,多语种,德语", lang: "德语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "de_male_sven_uranus_bigtts", name: "Sven", scene: "通用场景, 教学场景,多语种,德语", lang: "德语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "en_male_alberto_uranus_bigtts", name: "Alberto", scene: "通用场景, 教学场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_alex_uranus_bigtts", name: "Alex", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_allison_uranus_bigtts", name: "Allison", scene: "视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_bill_jones_corey_uranus_bigtts", name: "Bill", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "en_male_brad_pitt_p1_uranus_bigtts", name: "Brad_Pitt", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_brittney_uranus_bigtts", name: "Brittney", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_brittney_pimintel_uranus_bigtts", name: "Zoe", scene: "有声阅读, 客服场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "en_male_bruce_uranus_bigtts", name: "Adrian", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_chandler_p1_uranus_bigtts", name: "Leo", scene: "趣味口音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_cowboy_john_b_uranus_bigtts", name: "John", scene: "趣味口音, 角色扮演,美式英语,多语种", lang: "美式英语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "en_male_david_uranus_bigtts", name: "David", scene: "通用场景,有声阅读,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_diyuwenrounan_uranus_bigtts", name: "Julian", scene: "有声阅读,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_godfather_uranus_bigtts", name: "Godfather", scene: "有声阅读, 角色扮演,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_gollum_uranus_bigtts", name: "Gollum", scene: "角色扮演,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_hades_uranus_bigtts", name: "Beau", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_hayley_uranus_bigtts", name: "Hayley", scene: "教学场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_jamie_uranus_bigtts", name: "Jamie", scene: "通用场景, 教学场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_jane_uranus_bigtts", name: "Jane", scene: "视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_jenny_uranus_bigtts", name: "Jenny", scene: "通用场景, 客服场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_jidongchuanjiaoshi_uranus_bigtts", name: "Blaze", scene: "趣味口音, 角色扮演,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_jimmy_uranus_bigtts", name: "Jimmy", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_joanne_uranus_bigtts", name: "Joanne", scene: "通用场景,有声阅读, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_joker_uranus_bigtts", name: "Joker", scene: "趣味口音, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_josh_uranus_bigtts", name: "Josh", scene: "视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_josh_coery_uranus_bigtts", name: "Josiah", scene: "教学场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "en_male_kevin_uranus_bigtts", name: "Kevin", scene: "教学场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_knightley_uranus_bigtts", name: "Knightley", scene: "有声阅读,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_lana_del_rey_kelley_d_p1_uranus_bigtts", name: "Lynn", scene: "角色扮演,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_lana_del_rey_parky_s_p1_uranus_bigtts", name: "Ivy", scene: "客服场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_marcus_uranus_bigtts", name: "Marcus", scene: "通用场景,有声阅读,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_mel_uranus_bigtts", name: "Mel", scene: "教学场景, 客服场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_michael_uranus_bigtts", name: "Hank", scene: "通用场景, 教学场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_michael_kevin_uranus_bigtts", name: "Michael_Kevin", scene: "通用场景, 教学场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "en_female_myra_uranus_bigtts", name: "Myra", scene: "教学场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_myra_cmb_uranus_bigtts", name: "Sunny", scene: "教学场景, 客服场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "en_female_nadia_uranus_bigtts", name: "Blair", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_natasha_uranus_bigtts", name: "Natasha", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_rachel_p1_uranus_bigtts", name: "Rachel", scene: "趣味口音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_ronald_uranus_bigtts", name: "Ronald", scene: "有声阅读,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_russell_uranus_bigtts", name: "Russell", scene: "通用场景, 教学场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_scarlet_p1_uranus_bigtts", name: "Scarlet", scene: "客服场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_sharron_uranus_bigtts", name: "Sharron", scene: "趣味口音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_simba_p1_uranus_bigtts", name: "Simba", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_skye_uranus_bigtts", name: "Skye", scene: "通用场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_tom_hiddleston_p1_uranus_bigtts", name: "Tom", scene: "通用场景,有声阅读,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_valentino_uranus_bigtts", name: "Valentino", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_valentino_corey_uranus_bigtts", name: "Clark", scene: "视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "en_female_wenrouzhishijieshuonv_uranus_bigtts", name: "Megan", scene: "客服场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_xinwenjieshuonv_uranus_bigtts", name: "Kayla", scene: "角色扮演,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_male_yangguangjieshuonan_uranus_bigtts", name: "Dylan", scene: "通用场景, 视频配音,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "en_female_zendaya_p1_uranus_bigtts", name: "Zendaya", scene: "教学场景, 客服场景,美式英语,多语种", lang: "美式英语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "es_female_bv084_uranus_bigtts", name: "Gracie", scene: "通用场景, 客服场景,多语种,西班牙语", lang: "西班牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "es_male_dani_uranus_bigtts", name: "Dani", scene: "有声阅读,视频配音,多语种,西班牙语", lang: "西班牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "es_male_guillem_uranus_bigtts", name: "Guillem", scene: "有声阅读,多语种,西班牙语", lang: "西班牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "es_female_ht_mx_f6_uranus_bigtts", name: "Marisol", scene: "通用场景, 视频配音,多语种,西班牙语", lang: "西班牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "fr_female_fr_bv078_uranus_bigtts", name: "Simone", scene: "通用场景, 视频配音,多语种,法语", lang: "法语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "fr_female_fr_f47_uranus_bigtts", name: "Camille", scene: "教学场景, 客服场景,多语种,法语", lang: "法语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "fr_male_fr_m29_uranus_bigtts", name: "Maurice", scene: "有声阅读,视频配音,多语种,法语", lang: "法语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "fr_male_usseau_uranus_bigtts", name: "Usseau", scene: "通用场景, 客服场景,多语种,法语", lang: "法语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "id_male_bv160_uranus_bigtts", name: "Rocco", scene: "通用场景, 视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_male_bv160dialogue_uranus_bigtts", name: "Jude", scene: "通用场景, 视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_male_bv160narration_uranus_bigtts", name: "Hugo", scene: "有声阅读,视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_female_bv161_uranus_bigtts", name: "Clara", scene: "通用场景, 视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_female_bv161dialogue_uranus_bigtts", name: "Sylvia", scene: "通用场景, 视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_female_bv161narration_uranus_bigtts", name: "Celeste", scene: "通用场景, 视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_female_bv164_uranus_bigtts", name: "Crew", scene: "通用场景, 视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_male_bv164dialogue_uranus_bigtts", name: "Elian", scene: "视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_male_bv164narration_uranus_bigtts", name: "Ronan", scene: "有声阅读,视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_female_f20_uranus_bigtts", name: "Chloe", scene: "视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_male_han_uranus_bigtts", name: "Han", scene: "通用场景,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循、上下文遵循", group: "multilingual" },
  { voice_type: "id_male_m08_uranus_bigtts", name: "Kyle", scene: "通用场景, 教学场景,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "id_female_phulia_uranus_bigtts", name: "Phulia", scene: "通用场景, 视频配音,多语种,印尼语", lang: "印尼语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ja_female_bv024_uranus_bigtts", name: "Bonnie", scene: "通用场景, 教学场景,多语种,日语", lang: "日语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ja_female_bv520_uranus_bigtts", name: "Poppy", scene: "视频配音, 角色扮演,多语种,日语", lang: "日语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ja_female_bv521_uranus_bigtts", name: "Aoi", scene: "趣味口音, 角色扮演,多语种,日语", lang: "日语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ja_female_bv522_uranus_bigtts", name: "Hana", scene: "通用场景, 教学场景, 客服场景,多语种,日语", lang: "日语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ja_female_bv523_uranus_bigtts", name: "Lily", scene: "趣味口音, 角色扮演,多语种,日语", lang: "日语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ja_male_bv524_uranus_bigtts", name: "Ken", scene: "通用场景, 视频配音,多语种,日语", lang: "日语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ja_female_minimi_uranus_bigtts", name: "Minimi", scene: "通用场景, 视频配音,多语种,日语", lang: "日语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "ja_female_shirou_uranus_bigtts", name: "Shirou", scene: "视频配音, 角色扮演,多语种,日语", lang: "日语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ko_male_bv545_uranus_bigtts", name: "Jay", scene: "通用场景, 视频配音,多语种,韩语", lang: "韩语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ko_female_bv546_uranus_bigtts", name: "Momo", scene: "视频配音, 角色扮演,多语种,韩语", lang: "韩语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ko_male_m03_uranus_bigtts", name: "Minho", scene: "通用场景, 客服场景,多语种,韩语", lang: "韩语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ko_male_shane_uranus_bigtts", name: "Shane", scene: "有声阅读, 教学场景, 视频配音,多语种,韩语", lang: "韩语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "ms_male_ham_uranus_bigtts", name: "Ham", scene: "通用场景, 教学场景,多语种,马来语", lang: "马来语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ms_male_naim_uranus_bigtts", name: "Naim", scene: "通用场景, 客服场景,多语种,马来语", lang: "马来语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_female_bv065_uranus_bigtts", name: "Irene", scene: "教学场景, 视频配音,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_male_bv165dialogue_uranus_bigtts", name: "Diego", scene: "有声阅读,视频配音,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_male_bv165narrator_uranus_bigtts", name: "Marcos", scene: "有声阅读,视频配音,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_female_bv166dialogue_uranus_bigtts", name: "Lucy", scene: "通用场景, 视频配音,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_female_bv166emotion_uranus_bigtts", name: "Rosa", scene: "通用场景, 视频配音,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_female_bv166narrator_uranus_bigtts", name: "Freya", scene: "有声阅读, 视频配音, 客服场景,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_male_felipe_uranus_bigtts", name: "Felipe", scene: "通用场景,有声阅读,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "mx_male_ht_mx_m012_uranus_bigtts", name: "Derek", scene: "教学场景, 视频配音,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_female_leslie_uranus_bigtts", name: "Leslie", scene: "通用场景, 客服场景,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "mx_male_marcelo_uranus_bigtts", name: "Marcelo", scene: "通用场景, 视频配音,多语种,墨西哥西语", lang: "墨西哥西语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_male_bv172_uranus_bigtts", name: "Sam", scene: "通用场景, 客服场景,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_male_bv172dialogue_uranus_bigtts", name: "Walter", scene: "视频配音,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_male_bv172emotion_uranus_bigtts", name: "Vincent", scene: "教学场景, 视频配音,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_male_bv172narrator_uranus_bigtts", name: "Miles", scene: "有声阅读, 角色扮演,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_female_bv173_uranus_bigtts", name: "Diana", scene: "通用场景, 教学场景,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_female_bv173dialogue_uranus_bigtts", name: "Elena", scene: "视频配音, 客服场景,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_female_bv173emotion_uranus_bigtts", name: "Lola", scene: "通用场景, 教学场景,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_female_bv173narrator_uranus_bigtts", name: "Emma", scene: "视频配音, 客服场景,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_female_bv530_uranus_bigtts", name: "Sofia", scene: "通用场景, 视频配音,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_male_bv531_uranus_bigtts", name: "Arthur", scene: "通用场景, 教学场景,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_female_mari_uranus_bigtts", name: "Mari", scene: "教学场景, 视频配音,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "pt_male_martins_uranus_bigtts", name: "Toby", scene: "通用场景, 教学场景,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、上下文遵循", group: "multilingual" },
  { voice_type: "pt_male_rael_uranus_bigtts", name: "Rael", scene: "教学场景, 视频配音,多语种,巴西葡萄牙语", lang: "巴西葡萄牙语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ru_female_af07_uranus_bigtts", name: "Amelia", scene: "有声阅读,视频配音,多语种,俄语", lang: "俄语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ru_female_irinae_uranus_bigtts", name: "Irinae", scene: "有声阅读,视频配音,多语种,俄语", lang: "俄语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ru_male_pavel_uranus_bigtts", name: "Pavel", scene: "通用场景, 视频配音,多语种,俄语", lang: "俄语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ru_female_sophie_uranus_bigtts", name: "Ksenia", scene: "通用场景,多语种,俄语", lang: "俄语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "ru_male_vlad_uranus_bigtts", name: "Silas", scene: "趣味口音,多语种,俄语", lang: "俄语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "th_female_bv568_angry_uranus_bigtts", name: "Valeria", scene: "教学场景, 视频配音,多语种,泰语", lang: "泰语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "th_female_bv568_fear_uranus_bigtts", name: "Iris", scene: "有声阅读,视频配音,多语种,泰语", lang: "泰语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "th_female_bv568_happy_uranus_bigtts", name: "Zara", scene: "通用场景, 视频配音,多语种,泰语", lang: "泰语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "th_female_bv568_hate_uranus_bigtts", name: "Valentina", scene: "通用场景, 视频配音,多语种,泰语", lang: "泰语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "th_female_bv568_neutral_uranus_bigtts", name: "Mildred", scene: "通用场景, 视频配音,多语种,泰语", lang: "泰语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "th_female_bv568_sad_uranus_bigtts", name: "Lydia", scene: "视频配音, 客服场景,多语种,泰语", lang: "泰语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "th_female_bv568_suprise_uranus_bigtts", name: "Phoebe", scene: "有声阅读,视频配音,多语种,泰语", lang: "泰语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "tl_female_annika_uranus_bigtts", name: "Annika", scene: "通用场景, 视频配音,多语种,菲律宾语", lang: "菲律宾语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "tl_male_ed_uranus_bigtts", name: "Ed", scene: "通用场景, 视频配音,多语种,菲律宾语", lang: "菲律宾语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "tl_female_hervie_uranus_bigtts", name: "Hervie", scene: "有声阅读, 视频配音, 客服场景,多语种,菲律宾语", lang: "菲律宾语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "vi_female_hong_uranus_bigtts", name: "Hong", scene: "通用场景, 客服场景,多语种,越南语", lang: "越南语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "vi_female_ling_uranus_bigtts", name: "Ling", scene: "通用场景, 视频配音,多语种,越南语", lang: "越南语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "vi_female_linh_uranus_bigtts", name: "Linh", scene: "视频配音,多语种,越南语", lang: "越南语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "vi_female_partner_uranus_bigtts", name: "Partner", scene: "视频配音, 客服场景,多语种,越南语", lang: "越南语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "vi_female_ruan_uranus_bigtts", name: "Ruan", scene: "通用场景,有声阅读, 角色扮演,多语种,越南语", lang: "越南语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "vi_female_wu_uranus_bigtts", name: "Wu", scene: "通用场景, 视频配音,多语种,越南语", lang: "越南语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "vi_male_wumg_uranus_bigtts", name: "Wumg", scene: "通用场景, 客服场景,多语种,越南语", lang: "越南语", ability: "情感变化、指令遵循", group: "multilingual" },
  { voice_type: "it_male_enzo_uranus_bigtts", name: "Enzo", scene: "通用场景, 教学场景,多语种,意大利语", lang: "意大利语", ability: "情感变化、上下文遵循", group: "multilingual" },
]
